<a href="https://colab.research.google.com/github/cax68080/google_colab/blob/main/Python%E3%81%AB%E3%82%88%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E5%88%86%E6%9E%90%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8_CHAPTER_4_%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AB%E3%82%88%E3%82%8B%E5%88%86%E6%9E%90%E3%81%AE%E5%AE%9F%E8%B7%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##4.1 Numpyの基礎

- 一次元配列

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


- 2次元配列

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


- 変形(reshape)

In [ ]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [ ]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [ ]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

- データ型(dtype)

In [ ]:
print(a.dtype)

int64


In [ ]:
d = np.array([1,2],dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
d.dtype

dtype('int16')

In [ ]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

- インデックスとスライス

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(a[0])

1


In [ ]:
print(a[1:])

[2 3]


In [ ]:
print(a[-1])

3


In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b[0])

[1 2 3]


In [ ]:
print(b[1,0])

4


In [ ]:
print(b[:,2])

[3 6]


In [ ]:
print(b[1,:])

[4 5 6]


In [ ]:
print(b[0,1:])

[2 3]


In [ ]:
print(b[:,[0,2]])

[[1 3]
 [4 6]]


- データ再代入

In [ ]:
print(a)

[1 2 3]


In [ ]:
a[2] = 4
print(a)

[1 2 4]


In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[1,2] = 7
print(b)

[[1 2 3]
 [4 5 7]]


In [ ]:
b[:,2] = 8
print(b)

[[1 2 8]
 [4 5 8]]


- 深いコピー

In [ ]:
a1 = a
print(a1)

[1 2 4]


In [ ]:
a1[1] = 5
print(a1)
print(a)

[1 5 4]
[1 5 4]


In [ ]:
a2 = a.copy()
print(a2)

[1 5 4]


In [ ]:
a2[0] = 6
print(a2)
print(a)

[6 5 4]
[1 5 4]


In [ ]:
print(c2)

[[0 1 2]
 [3 4 5]]


In [ ]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7
print(c3)
print(c4)
print(c2)

[6 1 2 3 4 5]
[6 7 2 3 4 5]
[[6 1 2]
 [3 4 5]]


In [ ]:
py_list = [0,1]
py_list2 = py_list[:]
py_list2[0] = 2
print(py_list)
print(py_list2)

[0, 1]
[2, 1]


In [ ]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


- **数列を返す(arange)**

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
np.random.random((3,2))

array([[0.95308809, 0.25570871],
       [0.90346741, 0.44940346],
       [0.71967783, 0.22723423]])

In [6]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])