<a href="https://colab.research.google.com/github/cax68080/google_colab/blob/main/Python%E3%81%AB%E3%82%88%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E5%88%86%E6%9E%90%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8_CHAPTER_4_%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AB%E3%82%88%E3%82%8B%E5%88%86%E6%9E%90%E3%81%AE%E5%AE%9F%E8%B7%B5(4.1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##4.1 Numpyの基礎

- 一次元配列

In [3]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


- 2次元配列

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


- 変形(reshape)

In [ ]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [ ]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [ ]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

- データ型(dtype)

In [ ]:
print(a.dtype)

int64


In [ ]:
d = np.array([1,2],dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
d.dtype

dtype('int16')

In [ ]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

- インデックスとスライス

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(a[0])

1


In [ ]:
print(a[1:])

[2 3]


In [ ]:
print(a[-1])

3


In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b[0])

[1 2 3]


In [ ]:
print(b[1,0])

4


In [ ]:
print(b[:,2])

[3 6]


In [ ]:
print(b[1,:])

[4 5 6]


In [ ]:
print(b[0,1:])

[2 3]


In [ ]:
print(b[:,[0,2]])

[[1 3]
 [4 6]]


- データ再代入

In [ ]:
print(a)

[1 2 3]


In [ ]:
a[2] = 4
print(a)

[1 2 4]


In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[1,2] = 7
print(b)

[[1 2 3]
 [4 5 7]]


In [ ]:
b[:,2] = 8
print(b)

[[1 2 8]
 [4 5 8]]


- 深いコピー

In [ ]:
a1 = a
print(a1)

[1 2 4]


In [ ]:
a1[1] = 5
print(a1)
print(a)

[1 5 4]
[1 5 4]


In [ ]:
a2 = a.copy()
print(a2)

[1 5 4]


In [ ]:
a2[0] = 6
print(a2)
print(a)

[6 5 4]
[1 5 4]


In [ ]:
print(c2)

[[0 1 2]
 [3 4 5]]


In [ ]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7
print(c3)
print(c4)
print(c2)

[6 1 2 3 4 5]
[6 7 2 3 4 5]
[[6 1 2]
 [3 4 5]]


In [ ]:
py_list = [0,1]
py_list2 = py_list[:]
py_list2[0] = 2
print(py_list)
print(py_list2)

[0, 1]
[2, 1]


In [ ]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


- **数列を返す(arange)**

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

- 乱数

In [ ]:
np.random.random((3,2))

array([[0.95308809, 0.25570871],
       [0.90346741, 0.44940346],
       [0.71967783, 0.22723423]])

In [ ]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [ ]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [ ]:
np.random.seed(123)
np.random.randint(1,10)

3

In [ ]:
np.random.seed(123)
np.random.randint(1,100,(3,3))

array([[67, 93, 99],
       [18, 84, 58],
       [87, 98, 97]])

In [ ]:
np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [ ]:
np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [ ]:
np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

- 同じ要素の数列を作る

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- 単位行列

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- 指定値で埋める

In [ ]:
np.full((2,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [ ]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [ ]:
np.nan

nan

In [ ]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

- 範囲指定で均等割りデータを作る

In [ ]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

- 要素間の差分

In [ ]:
l = np.array([2,2,6,1,3])
np.diff(l)

array([ 0,  4, -5,  2])

In [ ]:
a = np.array([1,5,4])
a1 = np.array([1,5,4])
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [ ]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [4]:
b = np.array([[1,2,8],[4,5,8]])
b1 = np.array([[10],[20]])
print(b)
print(b1)

[[1 2 8]
 [4 5 8]]
[[10]
 [20]]


In [ ]:
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [ ]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [ ]:
b2 = np.array([30,60,45])
print(b2)

[30 60 45]


In [ ]:
b3 = np.vstack([b,b2])
print(b3)

[[ 1  2  8]
 [ 4  5  8]
 [30 60 45]]


- 分割

In [ ]:
first,second = np.hsplit(b3,[2])
print(first)
print(second)

[[ 1  2]
 [ 4  5]
 [30 60]]
[[ 8]
 [ 8]
 [45]]


In [ ]:
first1,second1 = np.vsplit(b3,[2])
print(first1)
print(second1)

[[1 2 8]
 [4 5 8]]
[[30 60 45]]


- 転置

In [ ]:
print(b)

[[1 2 8]
 [4 5 8]]


In [ ]:
print(b.T)

[[1 4]
 [2 5]
 [8 8]]


- 次元追加

In [ ]:
print(a)
print(a[np.newaxis,:])


[1 5 4]
[[1 5 4]]


In [ ]:
print(a[:,np.newaxis])


[[1]
 [5]
 [4]]


- グリッドデータの生成

In [ ]:
m = np.arange(0,4)
print(m)

[0 1 2 3]


In [ ]:
n = np.arange(4,7)
print(n)

[4 5 6]


In [ ]:
xx,yy = np.meshgrid(m,n)
print(xx)
print(yy)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


## **4.1.3 Numpyの各機能**

In [7]:
import numpy as np
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [ ]:
print("a:",a.shape)
print("b:",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


- ユニバーサルファンクション

In [1]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i,j in enumerate(li):
  new.append([])
  for k in j:
    new[i].append(abs(k))
print(new)

[[3, 2, 1], [0, 1, 2]]


In [8]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [9]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [10]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [11]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [12]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [13]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

- ブロードキャスト

In [14]:
print(a)

[0 1 2]


In [15]:
print(a + 10)

[10 11 12]


In [16]:
print(b)

[[-3 -2 -1]
 [ 0  1  2]]


In [17]:
print(b)

[[-3 -2 -1]
 [ 0  1  2]]


In [18]:
print(a + b)

[[-3 -1  1]
 [ 0  2  4]]


In [19]:
a1 = a[:,np.newaxis]
print(a1)

[[0]
 [1]
 [2]]


In [20]:
print(a + a1)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [21]:
print(c)

[[1 2 3]
 [4 5 6]]


In [22]:
print(np.mean(c))

3.5


In [25]:
print(abs(c - np.mean(c)))

[[2.5 1.5 0.5]
 [0.5 1.5 2.5]]


In [26]:
print(b)

[[-3 -2 -1]
 [ 0  1  2]]


In [27]:
print(b * 2)

[[-6 -4 -2]
 [ 0  2  4]]


In [28]:
print(b ** 3)

[[-27  -8  -1]
 [  0   1   8]]


In [29]:
print(b)
print(a)
print(b - a)

[[-3 -2 -1]
 [ 0  1  2]]
[0 1 2]
[[-3 -3 -3]
 [ 0  0  0]]


In [30]:
print(a * b)

[[ 0 -2 -2]
 [ 0  1  4]]


In [32]:
print(c)
print(a)
print(a / c)

[[1 2 3]
 [4 5 6]]
[0 1 2]
[[0.         0.5        0.66666667]
 [0.         0.2        0.33333333]]


In [33]:
print(c / a)

[[inf 2.  1.5]
 [inf 5.  3. ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [35]:
print(c / (a + 1e-6))

[[1.00000000e+06 1.99999800e+00 1.49999925e+00]
 [4.00000000e+06 4.99999500e+00 2.99999850e+00]]


- ドット積

In [36]:
print(a)
print(b)
print(np.dot(b,a))

[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[-4  5]


In [37]:
print(b @ a)

[-4  5]


In [39]:
print(b)
print(d)
print(b @ d)
print(d @ b)

[[-3 -2 -1]
 [ 0  1  2]]
[[0 1]
 [2 3]
 [4 5]]
[[ -8 -14]
 [ 10  13]]
[[  0   1   2]
 [ -6  -1   4]
 [-12  -3   6]]


- 判定・論理値

In [40]:
print(a)
print(a > 1)

[0 1 2]
[False False  True]


In [41]:
print(b)
print(b > 0)

[[-3 -2 -1]
 [ 0  1  2]]
[[False False False]
 [False  True  True]]


In [42]:
print(b)
np.count_nonzero(b > 0)

[[-3 -2 -1]
 [ 0  1  2]]


2

In [43]:
print(np.sum(b > 0))

2


In [44]:
print(np.any(b > 0))

True


In [45]:
print(np.all(b > 0))

False


In [46]:
print(b[b > 0])

[1 2]


In [47]:
print(b)
print(c)
print(b == c)

[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
[[False False False]
 [False False False]]


In [48]:
print(a)
print(b)
print(a == b)

[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[False False False]
 [ True  True  True]]


In [49]:
print(a)
print(b)
print(c)
print((b == c)|(a == b))

[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]


In [50]:
print(b[(b == c)|(a == b)])

[0 1 2]


In [51]:
print(np.allclose(b,c))

False


In [52]:
print(np.allclose(b,c,atol=10))

True


- 関数とメソッド

In [53]:
print(a)
np.sum(a)

[0 1 2]


3

In [54]:
print(a.sum())

3
